# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bcppvars <- function(prec, tmin, tmax) {
    .Call(`_meteor_bcppvars`, prec, tmin, tmax)
}

.utci <- function(ta, tg, va, hurs) {
    .Call(`_meteor_v_utci`, ta, tg, va, hurs)
}

.pwc_utci <- function(utci) {
    .Call(`_meteor_pwc_utci`, utci)
}

.pwc_wbgt <- function(wbgt) {
    .Call(`_meteor_pwc_wbgt`, wbgt)
}

.Tg1 <- function(tas, hurs, wind, srad, year, doy, lat) {
    .Call(`_meteor_Tg1`, tas, hurs, wind, srad, year, doy, lat)
}

.Tg2 <- function(tas, hurs, wind, srad, year, doy, lat) {
    .Call(`_meteor_Tg2`, tas, hurs, wind, srad, year, doy, lat)
}

.Tnwb1 <- function(tas, hurs, wind, srad, year, doy, lat, natural = TRUE) {
    .Call(`_meteor_Tnwb1`, tas, hurs, wind, srad, year, doy, lat, natural)
}

.Tnwb2 <- function(tas, hurs, wind, srad, year, doy, lat, natural = TRUE) {
    .Call(`_meteor_Tnwb2`, tas, hurs, wind, srad, year, doy, lat, natural)
}

.markov_rain <- function(rain, rainydays, years, markov, seed) {
    .Call(`_meteor_markov_rain`, rain, rainydays, years, markov, seed)
}

.hourlyFromDailyTemp <- function(tmin, tmax, doy, latitude) {
    .Call(`_meteor_hourlyFromDailyTemp`, tmin, tmax, doy, latitude)
}

.hourlyFromDailyRH <- function(relh, tmin, tmax, doy, latitude) {
    .Call(`_meteor_hourlyFromDailyRH`, relh, tmin, tmax, doy, latitude)
}

.Photoperiod <- function(doy, latitude) {
    .Call(`_meteor_Photoperiod`, doy, latitude)
}

.ET0_ThornthwaiteWilmott <- function(temp, doy, latitude) {
    .Call(`_meteor_ET0_ThornthwaiteWilmott`, temp, doy, latitude)
}

.ET0_ThornthwaiteWilmottCamargo <- function(tmin, tmax, doy, latitude, Pereira) {
    .Call(`_meteor_ET0_ThornthwaiteWilmottCamargo`, tmin, tmax, doy, latitude, Pereira)
}

.ET0_PenmanMonteith <- function(temp, relh, atmp, Rn, G, ra, rs) {
    .Call(`_meteor_ET0_PenmanMonteith`, temp, relh, atmp, Rn, G, ra, rs)
}

.ET0_PriestleyTaylor <- function(temp, relh, atmp, Rn, G) {
    .Call(`_meteor_ET0_PriestleyTaylor`, temp, relh, atmp, Rn, G)
}

.ET0_Makkink <- function(temp, relh, atmp, Rs) {
    .Call(`_meteor_ET0_Makkink`, temp, relh, atmp, Rs)
}

.E_Penman <- function(temp, relh, atmp, Rs, Rext, u, alpha, Z) {
    .Call(`_meteor_E_Penman`, temp, relh, atmp, Rs, Rext, u, alpha, Z)
}

.SVP <- function(temp) {
    .Call(`_meteor_SVP`, temp)
}

.VP <- function(temp, relh) {
    .Call(`_meteor_VP`, temp, relh)
}

.VPD <- function(temp, relh) {
    .Call(`_meteor_VPD`, temp, relh)
}

.ExtraTerrestrialRadiation <- function(doy, latitude, sc = 1367.7, FAO = FALSE) {
    .Call(`_meteor_ExtraTerrestrialRadiation`, doy, latitude, sc, FAO)
}

